export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Gaming } from './gaming/Gaming'
export { default as BlogPage } from './blogPage/BlogPage'
export { default as ProjectPage } from './project/ProjectPage'
export { default as ErrorPage } from './errorPage/ErrorPage'
export { default as Tutorial } from './tutorial/Tutorial'
